### ISSUE TITLE
Convert ICIRR affiliates document into an easier format

### ISSUE THREAD

**Issue by yjkogan** [chi-immigration-task-force/icirr-app#13]
(Assigned to Cat)

Right now we have a word document that's set up in columns that lists a bunch of ICIRR affiliates and the services they provide (checkboxes in each of four columns). It'd be great to have this in a format that's easier for a computer or map to consumer, maybe a CSV.

**Comment by cgreim** [comment]
@yjkogan totally forgot about this but I'm planning to do it tonight! could you share the word doc with me again?

**Comment by yjkogan** [comment]
@cgreim Sent!

**Comment by cgreim** [comment]
Here it is [in CSV format](https://drive.google.com/open?id=0BxRzivQ6cAr7NUhGZGFqbFo3Uzg)! Let me know if there are any changes that would make it easier to work with.

**Comment by yjkogan** [comment]
Thanks @cgreim!
