### ISSUE TITLE
Build the "Know Your Rights" screen

### ISSUE THREAD

**Issue by yjkogan** [chi-immigration-task-force/icirr-app#3]
Requirements of this screen:
- Display to the user organized and navigable information about their rights

Most important information can be found on ICIRR's [KYR card](http://www.icirr.org/content/documents/kyr_card_2017.pdf) One option would be to modify [this pdf](http://www.icirr.org/content/documents/kyr-eng_10305001_75c92e73f5bd19ba21a2a15cf9250dd291add554.pdf) so that we can scroll through it nicely in the app.

In general, resources about KYR can be found here: http://www.icirr.org/about/get-involved/know-your-rights-and-organize

**Comment by yjkogan** [comment]
Here's a mockup of some of the possible content.

![my rights](https://cloud.githubusercontent.com/assets/1165977/24988718/59ce83e2-1fcd-11e7-8372-4be28f3bbd86.png)

**Comment by gabivoicu** [comment]
@yjkogan Do you know what font that is in the mocks? Is it `Times`? I have an extension that claims that's what it is

**Comment by yjkogan** [comment]
I don't, but I'd just leave it as whatever's loading in. I think I set the default to be ICIRR's font (on their website).

**Comment by yjkogan** [comment]
If we want to restyle the font of the whole app we can at some point in the future :)

**Comment by gabivoicu** [comment]
@yjkogan Is there anything else to do here or can we close this issue?

**Comment by yjkogan** [comment]
Nope, I think we're all good! Thanks for the reminder :)

**Comment by gabivoicu** [comment]
Thank you, @yjkogan! I installed Trailer, a GitHub notifications manager, and now I'm finding 2-3 year old issues to close haha
